from typing import List

def eq_load_python(signal: List[float], m: float, neq: int, half: bool) -> float: ...
def eq_load_max_half_cycle_closed_python(signal: List[float], m: float, neq: int, half: bool) -> float: ...
def halfcycles(signal: List[float], half: bool) -> List[float]: ...
